### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by astro-fermi** [andreatramacere/jetset#27]
Hello Andrea,

I am learning to use jetset by working with the user guide. Most of the commands work well without any problem including MCMC fitting. However, I got an error when trying to generate the external photon field energy density along the jet. The input was:
fig = plt.figure(figsize=(8,6))
ax=fig.subplots(1)
N=50
G=1
R_range=np.logspace(13,25,N)
y=np.zeros((8,N))
my_jet.set_verbosity(0)
my_jet.set_par('R_BLR_in',1E17)
my_jet.set_par('R_BLR_out',1.1E17)
for ID,R in enumerate(R_range):
    my_jet.set_par('R_H',val=R)
    my_jet.set_external_fields()
    my_jet.energetic_report(verbose=False)

it threw the following error:
An exception has occurred, use %tb to see the full traceback.
SystemExit: JetkerneltException (line 111): the jetkernel failed
 exception message: enegetic name thisown not understood

I also have a physics question: when computing EC with the BLR, does it take into account the Klein-Nishina effect? Also, is the absorption of gamma-rays due to pair production with the BLR photons taken into account for the EC calculation? I guessed it because Donnea03 paper deals mainly with the gamma-ray absorption. If so, could you please add a small example about how one can plot the BLR opacity for gamma-gamma absorption as a function of photon energy or distance along the jet.

Thanks.

**Comment by andreatramacere** [comment]
Hi,
First of all thanks for using the code, and for the feedback.
1) I received a previous message regarding matplotlib, and segfault. can confirm that problem I need to fix the code. Please give me all the info, platform, cpu, python version etc...
2) can you send me the full notebook/script with the error for energetic report?
3) The internal absorption will be presente in the next release, including the external with the EBL

**Comment by astro-fermi** [comment]
Hi Andrea,
I use MAC OS Mojave 10.14.4, python 3.6.7, processor 2.9 GHz Intel Core i9.

It was a bit weird situation. Right after the installation, I tried the 'test_functions.test_short()' command and faced: 
1- 'no module named plt' error. Looking into the source code, I found that the command 'import pylab as plt' and then realized that matplotlib 3.0.2 (which was updated from 2.2.3 during the installation) doesn't have pylab. I reverted back to matplotlib 2.2.3 and then this issue was resolved.

2- Then, I ran the 'test_functions.test_short()' command again and this time faced the segmentation fault 11 error. Just for a try, I opened a new terminal and then ran the same command again and this time there was no error. I still have no idea why. 

Anyway, since the problem was sorted out, I went ahead and started working with the user guide. I was able to reproduce all the results successfully except the energy density plot. My input script is attached to this message as a text file and I get the following error:

/Users/XYZ/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/jet_model.py:76: UserWarning: 

********************************************************************************
Starting from version 1.1.0, the R parameter as default is linear 
and not logarithmic, please update your scripts
Also the format of the jet_model has changed, now it is a binary file.
********************************************************************************
  warnings.warn(m)
JetkerneltException (line 111): the jetkernel failed
 exception message: enegetic name thisown not understood




[test.py.txt](https://github.com/andreatramacere/jetset/files/4078215/test.py.txt)

**Comment by andreatramacere** [comment]
Hi,
1) yes indeed the problem of the segmentation fault is random only for a specific function,  and could be related to the C code,  but to be honest, I did not see in the past versions, so I need understand where it comes from!

2) regarding the script, I can't reproduce your error. If you are running in a notebook, can you please restart the kernel, or try to run in it in  ipython: ipython -i test.py
and see if the problem persists?
Cheers and thanks
  Andrea

**Comment by astro-fermi** [comment]
I just ran 'ipython -i try.py' and got the following output:
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
~/Downloads/Projects/Jet_Set_Test/test.py in <module>
     46     my_jet.set_par('R_H',val=R)
     47     my_jet.set_external_fields()
---> 48     my_jet.energetic_report(verbose=False)
     49 
     50     y[1,ID]=my_jet.energetic_dict['U_BLR_DRF']

~/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/jet_model.py in func_wrapper(*args, **kwargs)
    116            new_version_warning()
    117 
--> 118            raise JetkerneltException(message=message)
    119 
    120 

~/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/jet_model.py in __init__(self, message, debug_message)
     88 
     89     def __init__(self, message='Remote analysis exception', debug_message=''):
---> 90         super(JetkerneltException, self).__init__(message)
     91         self.message=message
     92         self.debug_message=debug_message

~/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/jet_model.py in __init__(self, msg)
     67             ln = inspect.currentframe().f_back.f_lineno
     68         self.args = "{0.__name__} (line {1}): {2}".format(type(self), ln, msg),
---> 69         sys.exit(self)
     70 
     71 def new_version_warning():

SystemExit: JetkerneltException (line 111): the jetkernel failed

 exception message: enegetic name thisown not understood

In [1]:

**Comment by andreatramacere** [comment]
Hi
Try to substitute the instruction:
   my_jet.energetic_dict['U_BLR_DRF']
with:
   my_jet.energetic_dict
just to see which are the keywords in the dictionary, and please cut and the paste the content of my_jet.energetic_dict in the next reply.
 Thanks Andrea

**Comment by astro-fermi** [comment]
I  think the problem lies with the following command:
my_jet.energetic_report(verbose=False)

if I put 'my_jet.energetic_dict' before it, I  get the following error:
AttributeError: 'Jet' object has no attribute 'energetic_dict'

**Comment by andreatramacere** [comment]
Hi, before the my_jet.energetic_report(verbose=False), the energetic_dict is not created, so it is normal that if you put it before my_jet.energetic_report(verbose=False), it should go always after.
try this:
```python
from jetset.jet_model import Jet
j=Jet()
j.add_EC_component('EC_BLR')
j.set_external_fields()
j.energetic_report(verbose=False)
j.energetic_dict
```
does it work?

**Comment by andreatramacere** [comment]
If the problem is still there It could be an issue with the swig wrapper. In case you can try install from the source and see if the problem is still there, on the other side, I will ad check in the python code to skip the 'thisown' keyword, and I will make a new release o conda.
I wait for your reply and thanks for your feedback

**Comment by astro-fermi** [comment]
Hi Andrea,
I'm sorry but the problem still persists even after I did a fresh installation. Swig is installed without any problem.  No worries, I will keep working on the other aspects of this nice package. I was thinking to use "energetic_report" command to compute various jet powers but I will wait for the next version. On Monday, I will also try running the  tool on a different computer (Ubuntu desktop) and will let you know if it works there.

**Comment by andreatramacere** [comment]
Hi,
if you are using the package installed from anaconda, then in principle your local swig should not be used. I will make this new release that will skip extra stuff added by swig, and I will fix also the issue with the new version of matplotlib. have a nice weekend and thanks again for the feedback! I will reply here when the new version is reday.

**Comment by andreatramacere** [comment]
Hi, I have made a new version to install from source:

https://github.com/andreatramacere/jetset/archive/p1.1.0.tar.gz

can you install it please? This should solve the matplotlib issue (try to use again version 3) and let me know what happens with energetic_dict.
I wait for your test to make new version 1.1.1 on anaconda
Thanks Andrea

**Comment by astro-fermi** [comment]
I just tested this version. Matplotlib issue still persists as I get the following error when running 'test_functions.test_short()' command:
Traceback (most recent call last):
  File "/Users/XYZ/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/plot_sedfit.py", line 12, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib.pyplot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XYZ/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/tests/test_functions.py", line 144, in test_short
    from jetset.plot_sedfit import  plt
  File "/Users/XYZ/miniconda3/lib/python3.6/site-packages/jetset-1.1.0-py3.6-macosx-10.7-x86_64.egg/jetset/plot_sedfit.py", line 16, in <module>
    from matplotlib import pylab as plt
ImportError: cannot import name 'pylab'

Anyway, I reverted back to Matplotlib 2.2.3 and this issue was resolved. Then I tested 'my_jet.energetic_report(verbose=False)' command. Unfortunately, I get the following error:

  warnings.warn(m)
JetkerneltException (line 112): the jetkernel failed

 exception message: local variable 'units' referenced before assignment

**Comment by andreatramacere** [comment]
OK,
thanks again. 
I have made a new tag:
https://github.com/andreatramacere/jetset/archive/pa1.1.0.tar.gz
can you try to run again with matplotlib 3. If the energetic_report fails you should get more info now. Anyhow, always with matplotlib 3 try these commands and let me know which works:
``` python
from matplotlib import  pyplot as plt
from matplotlib import pylab as plt
import  pylab as plt
```
Thanks!

**Comment by astro-fermi** [comment]
This time I tested a few other options also.
1- installing with conda install -c conda-forge --file requirements.txt
installs matplotlib 3.0.2 and it doesn't have any module  named pylab or pyplot. I get the following errors:
from matplotlib import  pyplot as plt
ImportError: cannot import name 'pyplot'
from matplotlib import pylab as plt
ImportError: cannot import name 'pylab'
import  pylab as plt
ModuleNotFoundError: No module named 'pylab'

2- Then, just for a try, I used another command for installation:
conda install --file requirements.txt

this time matplotlib was not updated to 3.0.2  and all went smoothly. And, finally, the error with energetic_report also vanished and I am able to  plot the energy density figure. Great help, thanks.

I am testing a few other commands and have a few doubts, mostly about extracting information, and will ask you in a few moments. Anyway, thanks for quickly responding to all the queries and making such a nice package available.

**Comment by andreatramacere** [comment]
Hi,
thanks to you.  I think the problem is conda-forge, there are many wrong things there! I will let you know when you can install from conda version 1.1.1. will update also the docs with fitting example for External Compton.
Thanks again for your help.
Cheers 
  Andrea

**Comment by astro-fermi** [comment]
Awesome, thanks. A few minor doubts:
a- could you please tell me the paper/reference where I can find the functional forms of the various particle distributions available within the package?

b- is it possible to extract particle distribution and save it to an array so that, if needed, I can plot or compare it with other distributions? I mean something like the manner with which syn and SSC flux values can be extracted with "my_jet.get_spectral_component_by_name" command.

c- I think the accretion disk spectrum computed by the tool is probably lower by a factor of 2 to its correct value. I attach a screenshot from a recent paper (Sbarrato et al. 2016, MNRAS, 462, 1542) which suggests that a factor of 2 comes from taking into account the anisotropy of the disk emission. This means if I take Ldisk = 1e45 erg/s, the peak of the disk spectrum should have a value ~1e45 erg/s. Currently it shows  ~5e44 erg/s. Please have a look.
<img width="541" alt="Screen Shot 2020-01-18 at 4 04 15 PM" src="https://user-images.githubusercontent.com/5036959/72666001-108f4780-3a0e-11ea-8d1e-06ef57334dd8.png">

**Comment by andreatramacere** [comment]
Hi,
a) for the log-parabolic particle distributions use the jetset reference papers. Power law,  broken power-law and pl cutoff are standard. The other like spitkov, is more complex. Anyhow I will add everything in the doc on readthedocs
b) yes
  ```python
from jetset.jet_model import Jet
j=Jet()
j.eval()
j.electron_distribution.gamma
j.electron_distribution.n_gamma
```
`j.electron_distribution.gamma`and `j.electron_distribution.n_gamma` are two numpy arrays.
if this is not in the docs, I will add it. Moreover you can also use in jetset an electron distribution that is a numpy array. 
c) I am using mostly the model of Ghisellini, but take into account that if you use BB or multi_BB, things can change, moreover a factor of 2 on disk luminosities is not that much given all the approximations used in theoretical disk models. I will ad more notes on the disk model in the doc, ti takes time... Anyhow if I am correct I divide by two the disk luminosities, because we see only one side of the disk.

Next week I have to teach a hands-on session in a PhD school for multi-messenger astronomy, so I will not be able to update all the docs before the school, can you please send me a reminder  next Friday? 
Cheers 
  Andrea

**Comment by andreatramacere** [comment]
Hi,
I have built v1.1.1 on conda. You can try it. To be sure that you are using v1.1.1, you should get this output 
```python
In [1]: import jetset

In [2]: jetset.__version__
Out[2]: '1.1.1'

In [3]: jetset.__label__
Out[3]: '04a76b69e30af95c7b81fa3a8d5a718bf4b5c69d'

In [4]:
```
Cheers and thanks
  Andrea

**Comment by andreatramacere** [comment]
Hi,
by the way, if you give me your name, I will add it to the list of testers that I will add to the new docs.

**Comment by astro-fermi** [comment]
Hi Andrea,

This is Vaidehi here :-).

I will try my best to assist you in developing this nice package.

**Comment by andreatramacere** [comment]
Thanks a lot Vaidehi, of course next step will be document temporal evolution ! :)
By the way, I was very curios to know who is working so much during weekend :D

**Comment by andreatramacere** [comment]
You are now among official testers:
https://jetset.readthedocs.io/en/latest/index.html
Cheers
  Andrea

**Comment by astro-fermi** [comment]
Hi @andreatramacere,
When you have some time, please update the documentation for 1.2.0 so that a user can start playing with the latest updates, especially temporal evolution ;)

**Comment by andreatramacere** [comment]
Hi @astro-fermi, I will do a zoom meeting to show all the new features, I will post a doodle on the FB page :)
